#ifndef EEPROM_CONFIG
#define EEPROM_CONFIG

#define EEPROM_SNAKE_CLASSIC_HIGHSCORE_ADDR 0
#define EEPROM_SNAKE_SPEED_HIGHSCORE_ADDR 4
#define EEPROM_SNAKE_RISING_HIGHSCORE_ADDR 8

#endif // EEPROM_CONFIG